# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'image_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\x0cimageservice\"Y\n\rUploadRequest\x12/\n\x08metadata\x18\x01 \x01(\x0b\x32\x1b.imageservice.ImageMetadataH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"7\n\rImageMetadata\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\"3\n\x0eUploadResponse\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\"!\n\x10\x44ownloadResponse\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"!\n\rDeleteRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0bListRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"7\n\x0cListResponse\x12\'\n\x06images\x18\x01 \x03(\x0b\x32\x17.imageservice.ImageInfo\"\'\n\x13GetImageInfoRequest\x12\x10\n\x08image_id\x18\x01 \x01(\t\"m\n\tImageInfo\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x12\n\nsize_bytes\x18\x03 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t2\x87\x03\n\x0cImageService\x12J\n\x0bUploadImage\x12\x1b.imageservice.UploadRequest\x1a\x1c.imageservice.UploadResponse(\x01\x12P\n\rDownloadImage\x12\x1d.imageservice.DownloadRequest\x1a\x1e.imageservice.DownloadResponse0\x01\x12H\n\x0b\x44\x65leteImage\x12\x1b.imageservice.DeleteRequest\x1a\x1c.imageservice.DeleteResponse\x12\x43\n\nListImages\x12\x19.imageservice.ListRequest\x1a\x1a.imageservice.ListResponse\x12J\n\x0cGetImageInfo\x12!.imageservice.GetImageInfoRequest\x1a\x17.imageservice.ImageInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=37
  _globals['_UPLOADREQUEST']._serialized_end=126
  _globals['_IMAGEMETADATA']._serialized_start=128
  _globals['_IMAGEMETADATA']._serialized_end=183
  _globals['_UPLOADRESPONSE']._serialized_start=185
  _globals['_UPLOADRESPONSE']._serialized_end=236
  _globals['_DOWNLOADREQUEST']._serialized_start=238
  _globals['_DOWNLOADREQUEST']._serialized_end=273
  _globals['_DOWNLOADRESPONSE']._serialized_start=275
  _globals['_DOWNLOADRESPONSE']._serialized_end=308
  _globals['_DELETEREQUEST']._serialized_start=310
  _globals['_DELETEREQUEST']._serialized_end=343
  _globals['_DELETERESPONSE']._serialized_start=345
  _globals['_DELETERESPONSE']._serialized_end=395
  _globals['_LISTREQUEST']._serialized_start=397
  _globals['_LISTREQUEST']._serialized_end=426
  _globals['_LISTRESPONSE']._serialized_start=428
  _globals['_LISTRESPONSE']._serialized_end=483
  _globals['_GETIMAGEINFOREQUEST']._serialized_start=485
  _globals['_GETIMAGEINFOREQUEST']._serialized_end=524
  _globals['_IMAGEINFO']._serialized_start=526
  _globals['_IMAGEINFO']._serialized_end=635
  _globals['_IMAGESERVICE']._serialized_start=638
  _globals['_IMAGESERVICE']._serialized_end=1029
# @@protoc_insertion_point(module_scope)
